
package org.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Tue Mar 21 00:31:44 CET 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "saveEventItemResponse", namespace = "http://org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveEventItemResponse", namespace = "http://org/")

public class SaveEventItemResponse {


}

