
package org.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Tue Mar 21 00:31:44 CET 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "saveEventItem", namespace = "http://org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveEventItem", namespace = "http://org/", propOrder = {"arg0", "arg1", "arg2"})

public class SaveEventItem {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private double arg1;
    @XmlElement(name = "arg2")
    private double arg2;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

    public double getArg2() {
        return this.arg2;
    }

    public void setArg2(double newArg2)  {
        this.arg2 = newArg2;
    }

}

