
package org;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-03-21T00:31:45.299+01:00
 * Generated source version: 3.5.5
 *
 */

public class ITripPlannerServer{

    protected ITripPlannerServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new org.TripPlanner();
        String address = "http://localhost:9090/TripPlannerPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new ITripPlannerServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

